using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Telbot.helper
{
    class CountryCode_helper
    {
        private static Dictionary<string, string> codes = new Dictionary<string, string>();

        public static Dictionary<string, string> getCodes()
        {
            init();
            return codes;
        }


        public static void init(){

            codes.Add("Iran", "98");
            codes.Add("Afghanistan", "93");
            codes.Add("Albania", "355");
            codes.Add("Algeria", "213");
            codes.Add("American Samoa", "1-684");
            codes.Add("Andorra", "376");
            codes.Add("Angola", "244");
            codes.Add("Anguilla", "1-264");
            codes.Add("Antarctica", "672");
            codes.Add("Antigua and Barbuda", "1-268");
            codes.Add("Argentina", "54");
            codes.Add("Armenia", "374");
            codes.Add("Aruba", "297");
            codes.Add("Australia", "61");
            codes.Add("Austria", "43");
            codes.Add("Azerbaijan", "994");
            codes.Add("Bahamas", "1-242");
            codes.Add("Bahrain", "973");
            codes.Add("Bangladesh", "880");
            codes.Add("Barbados", "1-246");
            codes.Add("Belarus", "375");
            codes.Add("Belgium", "32");
            codes.Add("Belize", "501");
            codes.Add("Benin", "229");
            codes.Add("Bermuda", "1-441");
            codes.Add("Bhutan", "975");
            codes.Add("Bolivia", "591");
            codes.Add("Bosnia and Herzegovina", "387");
            codes.Add("Botswana", "267");
            codes.Add("Brazil", "55");
            codes.Add("British Indian Ocean Territory", "246");
            codes.Add("British Virgin Islands", "1-284");
            codes.Add("Brunei", "673");
            codes.Add("Bulgaria", "359");
            codes.Add("Burkina Faso", "226");
            codes.Add("Burundi", "257");
            codes.Add("Cambodia", "855");
            codes.Add("Cameroon", "237");
            codes.Add("Canada", "1");
            codes.Add("Cape Verde", "238");
            codes.Add("Cayman Islands", "1-345");
            codes.Add("Central African Republic", "236");
            codes.Add("Chad", "235");
            codes.Add("Chile", "56");
            codes.Add("China", "86");
            codes.Add("Christmas Island", "61");
            codes.Add("Cocos Islands", "61");
            codes.Add("Colombia", "57");
            codes.Add("Comoros", "269");
            codes.Add("Cook Islands", "682");
            codes.Add("Costa Rica", "506");
            codes.Add("Croatia", "385");
            codes.Add("Cuba", "53");
            codes.Add("Curacao", "599");
            codes.Add("Cyprus", "357");
            codes.Add("Czech Republic", "420");
            codes.Add("Democratic Republic of the Congo", "243");
            codes.Add("Denmark", "45");
            codes.Add("Djibouti", "253");
            codes.Add("Dominica", "1-767");
            //codes.Add("Dominican Republic", "1-809, 1-829, 1-849");
            codes.Add("East Timor", "670");
            codes.Add("Ecuador", "593");
            codes.Add("Egypt", "20");
            codes.Add("El Salvador", "503");
            codes.Add("Equatorial Guinea", "240");
            codes.Add("Eritrea", "291");
            codes.Add("Estonia", "372");
            codes.Add("Ethiopia", "251");
            codes.Add("Falkland Islands", "500");
            codes.Add("Faroe Islands", "298");
            codes.Add("Fiji", "679");
            codes.Add("Finland", "358");
            codes.Add("France", "33");
            codes.Add("French Polynesia", "689");
            codes.Add("Gabon", "241");
            codes.Add("Gambia", "220");
            codes.Add("Georgia", "995");
            codes.Add("Germany", "49");
            codes.Add("Ghana", "233");
            codes.Add("Gibraltar", "350");
            codes.Add("Greece", "30");
            codes.Add("Greenland", "299");
            codes.Add("Grenada", "1-473");
            codes.Add("Guam", "1-671");
            codes.Add("Guatemala", "502");
            //codes.Add("Guernsey", "44-1481");
            codes.Add("Guinea", "224");
            codes.Add("Guinea-Bissau", "245");
            codes.Add("Guyana", "592");
            codes.Add("Haiti", "509");
            codes.Add("Honduras", "504");
            codes.Add("Hong Kong", "852");
            codes.Add("Hungary", "36");
            codes.Add("Iceland", "354");
            codes.Add("India", "91");
            codes.Add("Indonesia", "62");
            //codes.Add("Iran", "98");
            codes.Add("Iraq", "964");
            codes.Add("Ireland", "353");
            //codes.Add("Isle of Man", "44-1624");
            codes.Add("Israel", "972");
            codes.Add("Italy", "39");
            codes.Add("Ivory Coast", "225");
            codes.Add("Jamaica", "1-876");
            codes.Add("Japan", "81");
            //codes.Add("Jersey", "44-1534");
            codes.Add("Jordan", "962");
            codes.Add("Kazakhstan", "7");
            codes.Add("Kenya", "254");
            codes.Add("Kiribati", "686");
            codes.Add("Kosovo", "383");
            codes.Add("Kuwait", "965");
            codes.Add("Kyrgyzstan", "996");
            codes.Add("Laos", "856");
            codes.Add("Latvia", "371");
            codes.Add("Lebanon", "961");
            codes.Add("Lesotho", "266");
            codes.Add("Liberia", "231");
            codes.Add("Libya", "218");
            codes.Add("Liechtenstein", "423");
            codes.Add("Lithuania", "370");
            codes.Add("Luxembourg", "352");
            codes.Add("Macau", "853");
            codes.Add("Macedonia", "389");
            codes.Add("Madagascar", "261");
            codes.Add("Malawi", "265");
            codes.Add("Malaysia", "60");
            codes.Add("Maldives", "960");
            codes.Add("Mali", "223");
            codes.Add("Malta", "356");
            codes.Add("Marshall Islands", "692");
            codes.Add("Mauritania", "222");
            codes.Add("Mauritius", "230");
            codes.Add("Mayotte", "262");
            codes.Add("Mexico", "52");
            codes.Add("Micronesia", "691");
            codes.Add("Moldova", "373");
            codes.Add("Monaco", "377");
            codes.Add("Mongolia", "976");
            codes.Add("Montenegro", "382");
            codes.Add("Montserrat", "1-664");
            codes.Add("Morocco", "212");
            codes.Add("Mozambique", "258");
            codes.Add("Myanmar", "95");
            codes.Add("Namibia", "264");
            codes.Add("Nauru", "674");
            codes.Add("Nepal", "977");
            codes.Add("Netherlands", "31");
            codes.Add("Netherlands Antilles", "599");
            codes.Add("New Caledonia", "687");
            codes.Add("New Zealand", "64");
            codes.Add("Nicaragua", "505");
            codes.Add("Niger", "227");
            codes.Add("Nigeria", "234");
            codes.Add("Niue", "683");
            codes.Add("North Korea", "850");
            codes.Add("Northern Mariana Islands", "1-670");
            codes.Add("Norway", "47");
            codes.Add("Oman", "968");
            codes.Add("Pakistan", "92");
            codes.Add("Palau", "680");
            codes.Add("Palestine", "970");
            codes.Add("Panama", "507");
            codes.Add("Papua New Guinea", "675");
            codes.Add("Paraguay", "595");
            codes.Add("Peru", "51");
            codes.Add("Philippines", "63");
            codes.Add("Pitcairn", "64");
            codes.Add("Poland", "48");
            codes.Add("Portugal", "351");
            //codes.Add("Puerto Rico", "1-787, 1-939");
            codes.Add("Qatar", "974");
            codes.Add("Republic of the Congo", "242");
            codes.Add("Reunion", "262");
            codes.Add("Romania", "40");
            codes.Add("Russia", "7");
            codes.Add("Rwanda", "250");
            codes.Add("Saint Barthelemy", "590");
            codes.Add("Saint Helena", "290");
            codes.Add("Saint Kitts and Nevis", "1-869");
            codes.Add("Saint Lucia", "1-758");
            codes.Add("Saint Martin", "590");
            codes.Add("Saint Pierre and Miquelon", "508");
            codes.Add("Saint Vincent and the Grenadines", "1-784");
            codes.Add("Samoa", "685");
            codes.Add("San Marino", "378");
            codes.Add("Sao Tome and Principe", "239");
            codes.Add("Saudi Arabia", "966");
            codes.Add("Senegal", "221");
            codes.Add("Serbia", "381");
            codes.Add("Seychelles", "248");
            codes.Add("Sierra Leone", "232");
            codes.Add("Singapore", "65");
            codes.Add("Sint Maarten", "1-721");
            codes.Add("Slovakia", "421");
            //codes.Add("Slovenia", "386");
            codes.Add("Solomon Islands", "677");
            codes.Add("Somalia", "252");
            codes.Add("South Africa", "27");
            codes.Add("South Korea", "82");
            codes.Add("South Sudan", "211");
            codes.Add("Spain", "34");
            codes.Add("Sri Lanka", "94");
            codes.Add("Sudan", "249");
            codes.Add("Suriname", "597");
            codes.Add("Svalbard and Jan Mayen", "47");
            codes.Add("Swaziland", "268");
            codes.Add("Sweden", "46");
            codes.Add("Switzerland", "41");
            codes.Add("Syria", "963");
            codes.Add("Taiwan", "886");
            codes.Add("Tajikistan", "992");
            codes.Add("Tanzania", "255");
            codes.Add("Thailand", "66");
            codes.Add("Togo", "228");
            codes.Add("Tokelau", "690");
            codes.Add("Tonga", "676");
            codes.Add("Trinidad and Tobago", "1-868");
            codes.Add("Tunisia", "216");
            codes.Add("Turkey", "90");
            codes.Add("Turkmenistan", "993");
            codes.Add("Turks and Caicos Islands", "1-649");
            codes.Add("Tuvalu", "688");
            codes.Add("U.S. Virgin Islands", "1-340");
            codes.Add("Uganda", "256");
            codes.Add("Ukraine", "380");
            codes.Add("United Arab Emirates", "971");
            codes.Add("United Kingdom", "44");
            codes.Add("United States", "1");
            codes.Add("Uruguay", "598");
            codes.Add("Uzbekistan", "998");
            codes.Add("Vanuatu", "678");
            codes.Add("Vatican", "379");
            codes.Add("Venezuela", "58");
            codes.Add("Vietnam", "84");
            codes.Add("Wallis and Futuna", "681");
            codes.Add("Western Sahara", "212");
            codes.Add("Yemen", "967");
            codes.Add("Zambia", "260");
            codes.Add("Zimbabwe", "263");
        }



      
    }
}
